palette = "catppuccin_mocha"

format = "$directory $git_branch$git_status$cmd_duration $all"

[line_break]
disabled = false

[character]
success_symbol = "[ Œª](bold #cee9af)"
error_symbol = "[ Œª](bold #b0362c)"
vicmd_symbol = "[ Œª](bold maroon)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[directory]
style = "bold fg:#b3e4aa"
truncation_length = 3
fish_style_pwd_dir_length = 0
use_logical_path = true
disabled = false
read_only = 'üîí'
read_only_style = 'red'
truncation_symbol = ' '
home_symbol = ' ~'

[git_branch]
format = '[$symbol $branch(:$remote_branch)]($style) '
style = 'bold #e26d36'
symbol = 'Ôû° '

[git_status]
disabled = true

[battery]
disabled = true

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '


[docker_context]
symbol = "Ôåà "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[golang]
format = "[Ô≥ë $version](bold fg:#3e8fb0) "

[package]
disabled = true
symbol = "Ô£ñ "
format = "[$symbol$version]($style)"

[gcloud]
disabled = true

[rust]
style = "red"
symbol = "Óû® "
format = "[$symbol($version )]($style)"

[nodejs]
style = "bold fg:#ACE791"

[aws]
symbol = "ÓåΩ  "

[conda]
symbol = "ÔÑå "

[dart]
symbol = "Óûò "
format = "via [$symbol]($style)"

[elixir]
symbol = "Óâµ "
format = 'via [$symbol]($style)'

[elm]
symbol = "Óò¨ "

[java]
symbol = "Óâñ "
format = 'via [$symbol]($style)'

[julia]
symbol = "Óò§ "

[memory_usage]
symbol = "Ô°ö "

[nim]
symbol = "Ôö§ "

[nix_shell]
symbol = "Ôãú "

[perl]
symbol = "Óù© "

[php]
symbol = "Óòà "

[python]
symbol = "ÓòÜ "
format = 'via [$symbol]($style)'

[ruby]
symbol = "Óàæ "
disabled = true

[scala]
symbol = "Óú∑ "

[shlvl]
symbol = "ÔÑ† "

[swift]
symbol = "ÔØ£ "
format = 'via [$symbol]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
